https://numpy.org/doc/stable/reference/generated/numpy.ndarray.itemsize.html

https://jakevdp.github.io/PythonDataScienceHandbook/04.12-three-dimensional-plotting.html

# What is Numpy ?

* NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely. NumPy stands for **Numerical Python.**
* NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
* At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types
* NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

## Numpy Array Basics (ndarrays)

* In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy. Arrays are very frequently used in data science, where speed and resources are very important.
* Arrays in NumPy are synonymous with lists in Python with a homogenous nature. The homogeneity helps to perform smoother mathematical operations.
* These arrays are mutable. NumPy is useful to perform basic operations like finding the dimensions, the bite-size, and also the data types of elements of the array.

## Why is NumPy Faster Than Lists?

* NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called locality of reference in computer science. This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## 1. Creating Numpy Arrays/N-D arrays
>* To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [1]:
import numpy as np
'''it is a syntax to include the exeternal libraries 
into your code or current working file'''

'it is a syntax to include the exeternal libraries \ninto your code or current working file'

In [2]:
print(np.__version__) 
#check numpy version

1.21.5


>* first way of creating a nd-array in numpy
>* np.array()

In [3]:
# here we are creating a nd array from list 
arr1=np.array([1,2,3,4,5])
# checking data type of arr1
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
# we are using tuple to create numpy array
arr2 = np.array((1, 2, 3, 4, 5))
print(arr2)

[1 2 3 4 5]


In [6]:
# 2D ndarray
arr3=np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

>* using dtype to cahnge the data type of the given data

In [7]:
arr4 = np.array([1,2,3,4,5], dtype=float)
print(arr4)

[1. 2. 3. 4. 5.]


In [8]:
arr5 = np.array([0,1,2,3,4,5], dtype=bool)
print(arr5)

[False  True  True  True  True  True]


In [9]:
arr6 = np.array([1,2,3,4,5], dtype=complex)
print(arr6)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


>* creating ndarray with np.arange()

In [10]:
arr7=np.arange(10)
arr7
# range function will generate a "list" in a given range
# arange function will generate a "array" in a given range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr8=np.arange(10,21)
arr8

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
arr9=np.arange(10,21,2)
arr9

array([10, 12, 14, 16, 18, 20])

>* np.zeros(('order of the array'))
>* used in initialising the values

In [13]:
a = np.zeros((3,4),dtype=(np.int32))
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


>* np.ones(('order of the array'))
>* it is usefull to initialise the value in the neural network

In [14]:
b=np.ones((4,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

>* np.identity()
>* to create the identity matrix

In [15]:
c=np.identity(5)
c
# it is an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

>* np.random()
>* it will generate the random numbers between 0 to 1

In [16]:
d = np.random.random((4,5))
d

array([[0.56296356, 0.37307675, 0.02060265, 0.22479343, 0.97809145],
       [0.05267386, 0.37339304, 0.34442187, 0.94306163, 0.09131538],
       [0.44367886, 0.56904832, 0.74709168, 0.58898636, 0.13390639],
       [0.17425607, 0.04875341, 0.94199665, 0.92738867, 0.46429853]])

>* np.linspace()
>* linspace needs 3 parameters - upper range,lower range and spaced values

In [17]:
e=np.linspace(10,20,100)
e
# explore more about the linspace function
# linspace = linearly spaced

array([10.        , 10.1010101 , 10.2020202 , 10.3030303 , 10.4040404 ,
       10.50505051, 10.60606061, 10.70707071, 10.80808081, 10.90909091,
       11.01010101, 11.11111111, 11.21212121, 11.31313131, 11.41414141,
       11.51515152, 11.61616162, 11.71717172, 11.81818182, 11.91919192,
       12.02020202, 12.12121212, 12.22222222, 12.32323232, 12.42424242,
       12.52525253, 12.62626263, 12.72727273, 12.82828283, 12.92929293,
       13.03030303, 13.13131313, 13.23232323, 13.33333333, 13.43434343,
       13.53535354, 13.63636364, 13.73737374, 13.83838384, 13.93939394,
       14.04040404, 14.14141414, 14.24242424, 14.34343434, 14.44444444,
       14.54545455, 14.64646465, 14.74747475, 14.84848485, 14.94949495,
       15.05050505, 15.15151515, 15.25252525, 15.35353535, 15.45454545,
       15.55555556, 15.65656566, 15.75757576, 15.85858586, 15.95959596,
       16.06060606, 16.16161616, 16.26262626, 16.36363636, 16.46464646,
       16.56565657, 16.66666667, 16.76767677, 16.86868687, 16.96

In [18]:
g=e.copy()
g

array([10.        , 10.1010101 , 10.2020202 , 10.3030303 , 10.4040404 ,
       10.50505051, 10.60606061, 10.70707071, 10.80808081, 10.90909091,
       11.01010101, 11.11111111, 11.21212121, 11.31313131, 11.41414141,
       11.51515152, 11.61616162, 11.71717172, 11.81818182, 11.91919192,
       12.02020202, 12.12121212, 12.22222222, 12.32323232, 12.42424242,
       12.52525253, 12.62626263, 12.72727273, 12.82828283, 12.92929293,
       13.03030303, 13.13131313, 13.23232323, 13.33333333, 13.43434343,
       13.53535354, 13.63636364, 13.73737374, 13.83838384, 13.93939394,
       14.04040404, 14.14141414, 14.24242424, 14.34343434, 14.44444444,
       14.54545455, 14.64646465, 14.74747475, 14.84848485, 14.94949495,
       15.05050505, 15.15151515, 15.25252525, 15.35353535, 15.45454545,
       15.55555556, 15.65656566, 15.75757576, 15.85858586, 15.95959596,
       16.06060606, 16.16161616, 16.26262626, 16.36363636, 16.46464646,
       16.56565657, 16.66666667, 16.76767677, 16.86868687, 16.96

In [19]:
f=np.linspace(10,20,10, dtype=int)
f

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])

>* np.empty()
>>* The .empty() function creates an array with empty values 
>* np.full()
>>* and the full() function creates an n*n array with the given value.

In [20]:
arr15=np.empty((2,3))
print("arr15 is : ",arr15)
arr16=np.full((2,2), 3)
print("arr16 is : ",arr16)

arr15 is :  [[0. 0. 0.]
 [0. 0. 0.]]
arr16 is :  [[3 3]
 [3 3]]


* **Note :** by default numpy arrays will create a floating values

## 2. Numpy Array Properties and Attributes
1. Shape 
2. nDim
3. Size
4. Itemsize
5. Dtype
6. astype()

In [21]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### 1  .shape

In [22]:
a1.shape
# here shape is the attribute so we will not use tha brackets ()
# shape is an attribute or characteristic of the array

(10,)

In [23]:
a2.shape

(3, 4)

In [24]:
print(a3.shape)
a3
# here a3 array is made up of 2 2D arrays
# and each 2D array is made up of 2 1D arrays

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
arr9.shape
# it's a three dimensional matrix
# explore about the three dimensional matrix how does it look

(2, 2, 2)

### 2  .ndim
to get the dimensions of the ndarray

In [27]:
a3.ndim
# three dimensinal

3

In [28]:
a2.ndim
# 2 dimensional

2

In [29]:
a1.ndim
# 1 dimensional

1

In [30]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions : 5


note:
* reason why functions has a bracket is because it always asks any sort of input from the user which will be processed by that function and then will provide the output whereas attributes do not have brackets, it directly gives the output
* if function is in use then we will use the bracket
* where as if the attribute of the function is being used then we will not use the bracket

### 3   .size
Number of elements in the array.

In [31]:
print(a1)
a1.size
# number of items = size

[0 1 2 3 4 5 6 7 8 9]


10

In [32]:
print(a2)
a2.size

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


12

In [33]:
print(a3)
a3.size
# here number of items are 8

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


8

### 4  .itemsize
* This attribute gives the memory size of one element of NumPy array in bytes.
* Length of one array element in bytes.

In [34]:
print(a1)
a1.itemsize

[0 1 2 3 4 5 6 7 8 9]


4

In [35]:
a2.itemsize
# size of float will be more

8

In [36]:
a3.itemsize
# size of integer will be less

4

In [37]:
x = np.zeros((3, 5, 2), dtype=np.complex128)
x

array([[[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]]])

In [38]:
x.size
# total number of items

30

In [39]:
x.itemsize
# memory occupation of elements

16

### 5 .dtype

### Data Types in NumPy
* NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
* Below is a list of all data types in NumPy and the characters used to represent them.
1. i - integer
2. b - boolean 
3. u - unsigned integer 
4. f - float 
5. c - complex float 
6. m - timedelta 
7. M - datetime 
8. O - object 
9. S - string 
10. U - unicode string 
11. V - fixed chunk of memory for other type ( void )

In [40]:
a1.dtype

dtype('int32')

In [41]:
a2.dtype

dtype('float64')

In [42]:
a3.dtype

dtype('int32')

In [43]:
#create a array with data type unicode stirng :
arr = np.array([1, 2, 3, 4], dtype=str)
print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U1


In [44]:
#Create an array with data type complex:
arr1 = np.array([1, 2, 3, 4], dtype=complex)
print(arr1)
print(arr1.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


### 6 .astype
* if you want then you can convert a type of data inside a numpy array

#### Converting Data Type on Existing Arrays
* The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
* The astype() function creates a copy of the array, and allows you to specify the data type as a parameter. The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer

In [45]:
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr9)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
print(arr9.astype("float"))
'''this function will be useful when we have to clean the data, 
in that we have to clear the footprint of the data 
it means we have to reduce the size of the data
it's like age was stored in the floating data type then 
we have to work on it by converting it into datatype that we want
'''

[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


"this function will be useful when we have to clean the data, \nin that we have to clear the footprint of the data \nit means we have to reduce the size of the data\nit's like age was stored in the floating data type then \nwe have to work on it by converting it into datatype that we want\n"

In [47]:
print(a2.dtype)
print(a2.astype("int"))
print(a2.astype("complex"))

float64
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j]
 [ 4.+0.j  5.+0.j  6.+0.j  7.+0.j]
 [ 8.+0.j  9.+0.j 10.+0.j 11.+0.j]]


In [48]:
print("Given array is : ",a3)
print("Data type of the array a3 is : ",a3.dtype)
print("Converted data type of a3 is : ",a3.astype(np.float64))

Given array is :  [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Data type of the array a3 is :  int32
Converted data type of a3 is :  [[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]


In [49]:
#change data type float into integer
arr = np.array([1.1, 2.1, 3.1])
print(arr)
print(arr.dtype)
newarr = arr.astype(np.int32)
print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
float64
[1 2 3]
int32


actually when large amount of data is in floating data type then it will consume the large size of memory and when we will run this floating value data on the algorithm then it will run slow so eventually we will convert this data type in the integer data type and it will consume the half of the memory and it will run faster on the algorithm and reason for doing this was we don't needed the floating data type

In [50]:
#creating the random three-dimensional matrix   
matrix1 = np.random.randint(0, 10, size=(3, 5, 2))  
matrix2 = np.random.randint(0, 10, size=(3, 2, 5))  

In [51]:
matrix1

array([[[2, 3],
        [8, 7],
        [7, 1],
        [0, 9],
        [3, 2]],

       [[9, 2],
        [5, 7],
        [9, 1],
        [0, 3],
        [1, 7]],

       [[4, 0],
        [1, 1],
        [7, 5],
        [1, 5],
        [1, 5]]])

In [52]:
matrix2

array([[[6, 4, 5, 0, 1],
        [9, 3, 4, 7, 8]],

       [[3, 6, 6, 0, 7],
        [2, 2, 3, 9, 1]],

       [[8, 0, 8, 0, 9],
        [9, 9, 8, 6, 1]]])

* so basically when we are editing the videos or photos or any 3d pic, we are not editing those object but in real we are converting those videos or 3D photos in the matrix form, it may be of 2D or 3D or n dimensional and we are editing those data types in which those objects are stored.