In [1]:
import numpy as np

# 1. Indexing & Slicing
* if we take out one item then it is indexing 
* if we take out multiple items from the data it is called as slicing

In [2]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


## a. Indexing

In [3]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a1[0]

0

In [5]:
a1[-1]

9

In [6]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
# get 6
a2[1][2]

6

In [8]:
# other way to get 6
a2[1,2]

6

In [9]:
# get 11
a2[2,3]

11

In [10]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [11]:
# get 3
a3[0][1][1]

3

In [12]:
# other way to get 3
a3[0,1,1]

3

In [13]:
# get 5
a3[1,0,1]

5

In [14]:
# get 6
a3[1,1,0]

6

## b. Slicing arrays
* Slicing in python means taking elements from one given index to another given index.
* We pass slice instead of index like this: [start:end].
* We can also define the step, like this: [start:end:step].
* If we don't pass start its considered 0

* If we don't pass end its considered length of array in that dimension
* If we don't pass step its considered 1


In [15]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
# get 2,3,4
a1[2:5]

array([2, 3, 4])

In [17]:
# get 6,7,8
a1[-4:-1]

array([6, 7, 8])

In [18]:
a1[::2]

array([0, 2, 4, 6, 8])

In [19]:
a1[::-1]
# reversing the array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
# get the first row
a2[0]

array([0, 1, 2, 3])

In [22]:
# another way to get the first row
a2[0,:]

array([0, 1, 2, 3])

In [23]:
# we want third column
a2[:,2:3]

array([[ 2],
       [ 6],
       [10]])

In [24]:
# we want 7,11
a2[1:,3:]

array([[ 7],
       [11]])

In [25]:
# get 2,6
a2[:2,2:3]

array([[2],
       [6]])

In [26]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
# we want 5,6 and 9,10
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [28]:
# we want 1,2 and 9,10
a2[0::2,1:3]

array([[ 1,  2],
       [ 9, 10]])

In [29]:
# we want 0,3,8,11
a2[0::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [30]:
# get 4 and 7
a2[1:2,::3]

array([[4, 7]])

In [31]:
# get 1,3,9,11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [32]:
a4 = np.arange(27).reshape(3,3,3)
print(a4)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [33]:
# we want middle 2D array
a4[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [34]:
# we want first and last 2D array
a4[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
# we want secong row of the first 2D array
a4[0,1,:]

array([3, 4, 5])

In [36]:
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [37]:
# we want sceond 2D array and middle column
a4[1,:,1]

array([10, 13, 16])

In [38]:
# we want 22, 23, 25, 26
a4[2,1:3,1:3]

array([[22, 23],
       [25, 26]])

In [39]:
# we want 0,2,18,20
a4[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [40]:
#access array element using indexing
arr = np.array([1, 2, 3, 4])
print(arr[1])
#add two element in array using indexing
print(arr[2] + arr[3]) 

2
7


# 2. Iteration

In [41]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [42]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [43]:
for i in a2:
    print(i)
# in 2D array it will print the row every time

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [44]:
for i in a3:
    print(i)
# in 3D array it will print 2D array every time

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [45]:
for i in a4:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


>* if we want to print every item of the array then we can use np.nditer() function

In [46]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [47]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7


In [48]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [50]:
# this will give you all the items of the nd arrays
for i in np.nditer(arr12):
    print(i)
'''it's an inbuilt function of the numpy array - 
np.nditer('name of the nd-arrays')'''    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


"it's an inbuilt function of the numpy array - \nnp.nditer('name of the nd-arrays')"