In [1]:
import numpy as np

#  1.Array Operations

In [2]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## a. Scalar operations

In [3]:
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


#### Arithmetic

In [4]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [5]:
a1+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [6]:
a1/3

array([[0.        , 0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        , 2.33333333],
       [2.66666667, 3.        , 3.33333333, 3.66666667]])

In [7]:
a1-4

array([[-4, -3, -2, -1],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

#### relational

In [8]:
a2 > 16

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [9]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [10]:
a2 !=13

array([[ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## b. Vector operations

In [11]:
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


#### arithmetic

In [12]:
a1 + a2
# addition will be done item wise

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [13]:
a1 * a2
# element wise multiplication

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [14]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [15]:
a1-a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

#### relational

In [16]:
a1 > a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [17]:
a1 != a2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# 2.Array functions

In [18]:
a1 = np.random.random((3,3))
print(a1)
# this will give random number between the range 0 and 1
a1 = np.round(a1*100)
print(a1)

[[0.05280051 0.94351476 0.44512429]
 [0.30466123 0.78173447 0.39690614]
 [0.82086472 0.19299602 0.21066361]]
[[ 5. 94. 45.]
 [30. 78. 40.]
 [82. 19. 21.]]


#### max / min / sum / prod
>* axis=0 it is column
>* axis=1 it is row

In [19]:
np.max(a1)

94.0

In [20]:
np.min(a1)

5.0

In [21]:
# if we want minimum value of particular axis then
# if axis=0 then it will give column wise minimum value
np.min(a1, axis=0)

array([ 5., 19., 21.])

In [22]:
np.min(a1, axis=1)
# here axis = 1 so it wili work on rows

array([ 5., 30., 19.])

In [23]:
np.sum(a1)

414.0

In [24]:
np.sum(a1, axis=1)
# row wise sum

array([144., 148., 122.])

In [25]:
np.prod(a1)
# product

64769861520000.0

In [26]:
np.prod(a1, axis=0)
# product of column values

array([ 12300., 139308.,  37800.])

In [27]:
np.prod(a1, axis=1)
# product of row values

array([21150., 93600., 32718.])

#### mean / median / std / var

In [28]:
np.mean(a1)

46.0

In [29]:
np.mean(a1, axis=0)
# mean of each column

array([39.        , 63.66666667, 35.33333333])

In [30]:
np.median(a1)

40.0

In [31]:
np.std(a1)

29.724662412810606

In [32]:
np.var(a1)

883.5555555555555

#### trignometry

In [33]:
np.sin(a1)

array([[-0.95892427, -0.24525199,  0.85090352],
       [-0.98803162,  0.51397846,  0.74511316],
       [ 0.31322878,  0.14987721,  0.83665564]])

#### dot product

In [34]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
print(a2)
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [35]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [36]:
# other way for dot multiplication
a2.dot(a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

#### log and exponent

In [37]:
a1

array([[ 5., 94., 45.],
       [30., 78., 40.],
       [82., 19., 21.]])

In [38]:
np.log(a1)

array([[1.60943791, 4.54329478, 3.80666249],
       [3.40119738, 4.35670883, 3.68887945],
       [4.40671925, 2.94443898, 3.04452244]])

In [39]:
np.exp(a1)
# exponent

array([[1.48413159e+02, 6.66317622e+40, 3.49342711e+19],
       [1.06864746e+13, 7.49841700e+33, 2.35385267e+17],
       [4.09399696e+35, 1.78482301e+08, 1.31881573e+09]])

#### round / floor / ceil

In [40]:
a = np.random.random((3,4))
print(a)
# we will get random values between 0 to 1
print(a*100)
# we are multiplying it with 100
np.round(a*100)
# now we will round off the values

[[0.03715298 0.11202358 0.61570176 0.49187984]
 [0.17497281 0.33208759 0.76517829 0.73157945]
 [0.96724768 0.4909146  0.03374055 0.48535071]]
[[ 3.7152976  11.20235786 61.57017552 49.18798366]
 [17.49728092 33.20875946 76.51782927 73.15794481]
 [96.72476801 49.09146021  3.37405533 48.53507053]]


array([[ 4., 11., 62., 49.],
       [17., 33., 77., 73.],
       [97., 49.,  3., 49.]])

In [41]:
a = np.random.random((3,4))
print(a)
# we will get random values between 0 to 1
print(a*100)
# we are multiplying it with 100
np.floor(a*100)
# now we will floor the values

[[0.88866875 0.60975317 0.02474568 0.86747306]
 [0.87344352 0.88191743 0.03250947 0.19022624]
 [0.19535778 0.32757358 0.26311876 0.97845519]]
[[88.86687514 60.97531655  2.47456774 86.74730553]
 [87.3443518  88.19174275  3.25094695 19.02262448]
 [19.5357784  32.75735805 26.31187584 97.84551919]]


array([[88., 60.,  2., 86.],
       [87., 88.,  3., 19.],
       [19., 32., 26., 97.]])

In [42]:
a = np.random.random((3,4))
print(a)
# we will get random values between 0 to 1
print(a*100)
# we are multiplying it with 100
np.ceil(a*100)
# now we will ceil the values

[[0.540061   0.9357802  0.65119419 0.91937551]
 [0.06579472 0.81104232 0.23913648 0.94445207]
 [0.70762951 0.56467164 0.02456476 0.33561083]]
[[54.00609998 93.57801978 65.11941916 91.93755141]
 [ 6.57947167 81.10423191 23.9136477  94.44520668]
 [70.76295054 56.46716382  2.45647648 33.56108261]]


array([[55., 94., 66., 92.],
       [ 7., 82., 24., 95.],
       [71., 57.,  3., 34.]])

>* **Note :** after typing np. press tab key to get all available function within that np. syntax

# 3.Reshaping numpy arrays
>1. Reshape
>2. Transpose
>3. Ravel

### 1. Reshape
> np.reshape(a, newshape, order='C)
* Gives a new shape to an array without changing its data.

In [43]:
a1=np.arange(24)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
np.reshape(a1,(8,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [45]:
np.reshape(a1,(12,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [46]:
np.reshape(a1,(6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [48]:
np.reshape(a,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
b = np.arange(16).reshape(2,2,2,2)
b
# 4D array will be created

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [50]:
np.reshape(b,(2,2,4))
# 3D array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

### 2. Transpose
> np.transpose(a, axes=None)

Returns an array with axes transposed.
>* ndarray.transpose is Equivalent method.

In [51]:
'''For a 1-D array, it returns an unchanged view of the original array, 
as a transposed vector is simply the same vector
'''
a = np.array([1, 2, 3, 4])
print(a)
np.transpose(a)

[1 2 3 4]


array([1, 2, 3, 4])

In [52]:
b = np.arange(8).reshape(2,4)
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [53]:
b.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [54]:
b.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [55]:
np.transpose(b)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

### 3. Ravel
>* The numpy.ravel() functions returns contiguous flattened array(1D array with all the input-array elements and with the same type as it). A copy is made only if needed. 
>* it will bring higehr dimension array to 1D without losing any information
* **Syntax :**     
>* np.ravel(array, order = 'C')

In [56]:
b = np.arange(16).reshape(2,2,2,2)
b
# 4D array will be created

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [57]:
print(np.ravel(b))
# it will return 1D array
print(np.ravel(b).ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1


In [58]:
b.ravel()
# other way of writing ravel function

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# 4.Stacking
>1. horizontal stacking
>2. vertical stacking

* stack() is used for joining multiple NumPy arrays. 
* Unlike, concatenate(), it joins arrays along a new axis.
* If axis is not explicitly passed, it is taken as 0.
* It returns a NumPy array. 
* to join 2 arrays, they must have the same shape and dimensions.

* stack() creates a new array which has 1 more dimension than the input arrays. If we stack two 1-D arrays, the resultant array will have 2 dimensions.

In [59]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


#### 1. horizontal stacking

In [60]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [61]:
np.hstack((a4,a5,a4))
# we can join as many array as we want

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

#### 2.vertical stacking 

In [62]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
np.vstack((a4,a5,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
# input array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a)
print(b)

print(a.ndim)
print(b.ndim)

# Stacking two 1-d arrays
c = np.stack((a, b),axis=0)
print(c)
c.ndim

[1 2 3]
[4 5 6]
1
1
[[1 2 3]
 [4 5 6]]


2

In [65]:
# stack two 1-d arrays column - wise
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [66]:
# input arrays
x=np.array([[1,2,3],
            [4,5,6]])
 
y=np.array([[7,8,9],
            [10,11,12]])
print(x)
print(x.ndim)
print(y)
print(y.ndim)

[[1 2 3]
 [4 5 6]]
2
[[ 7  8  9]
 [10 11 12]]
2


In [67]:
# stacking with axis=0

a=np.stack((x,y),axis=0)
print(a)
print(a.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [68]:
# stacking with axis=1

b=np.stack((x,y),axis=1)
print(b)
print(b.ndim)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
3


In [69]:
'''NumPy provides a helper function: dstack() 
to stack along height, which is the same as depth.'''

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# 5. Splitting 
>* Splitting is reverse operation of Joining.
>* Joining merges multiple arrays into one and Splitting breaks one array into multiple.

#### 1. hsplit()

In [70]:
a4 = np.arange(12).reshape(3,4)
print(a4)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [71]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

#### 2.vsplit()

In [72]:
a5 = np.arange(12,24).reshape(3,4)
print(a5)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [73]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [74]:
'''Use the hsplit() method to split the 2-D array 
into three 2-D arrays along rows.'''

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], 
                [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [75]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [76]:
'''Use the vsplit() method to split the 2-D array 
into three 2-D arrays along columns.'''

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], 
                [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [77]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]


In [78]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)
#  The return value is an array containing three arrays.

[array([1, 2]), array([3, 4]), array([5, 6])]


* The return value of the array_split() method is an array containing each of the split as an array.
* If you split an array into 3 arrays, you can access them from the result just like any array element:

In [79]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [80]:
# If the array has less elements than required, it will adjust from the end accordingly.
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [81]:
# Split the 2-D array into three 2-D arrays.

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [82]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


* In addition, you can specify which axis you want to do the split around.
* The example below also returns three 2-D arrays, but they are split along the row (axis=1).

In [83]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [84]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [86]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=0)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
