In [1]:
import numpy as np

# 1. Numpy Array Vs. Python Lists
* python list data type will not be usefull when we want to apply the machine learning algorithms, that's why we are using the nd array or numpy array data type
>* **Benefits of using numpy :**
    >1. Faster
    >2. Convenient
    >3. Less memory

#### 1.faster speed

In [2]:
# time taken by list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
''' we are creating two list with 1 crore items'''

' we are creating two list with 1 crore items'

In [3]:
c = []

import time 

start = time.time()

for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)

2.554750680923462


In [4]:
#  time taken by NumPy array
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.09445667266845703


* from above two cell we can say that numpy arrays take lesser time in executing the code

#### 2.less memory
* for the same number of items, numpy array occupies less size of the memory than list

In [5]:
# we are making a python list with 1 crore items
a = [i for i in range(10000000)]

import sys
sys.getsizeof(a)

89095160

In [6]:
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000104

#### 3.convenience
* codes are easy to write

# 2. Advanced indexing

In [7]:
# Normal Indexing and slicing
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
a[1,2]

5

In [9]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

## a. fancy indexing

In [10]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

>* if we want first, third and fourth row
>* here in such cases we can not use normal indexing

In [11]:
a[[0,2,3]]
# here we are passing list of rows that we want

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
# we want 1,3,4,6 row
b[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [14]:
# we want 1,2 and 4th column
b[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

## b. Boolean indexing
* we can do conditional indexing and get the items accordingly
* suppose we want values which are >50, in such case we can use python operators and we can send it inside 
* result will be the array with the same shape and the resultant array is a boolean array

In [15]:
a = np.random.randint(low=1,high=100,size=24).reshape(6,4)
a

array([[12, 14, 45, 17],
       [80, 22, 14, 75],
       [38, 76, 53, 66],
       [73, 93, 92, 71],
       [86, 50, 88, 48],
       [48, 94, 46, 41]])

>* find all numbers greater than 50

In [16]:
a > 50
# here item wise comparision will be done
'''we will get the boolean array because
every item inside the array is True or False '''

'we will get the boolean array because\nevery item inside the array is True or False '

In [17]:
'''now we can use the above boolean array as mask,
and we can do filtering through that,
here we will pick the boolean array and 
put it in the original array
then we will get the values according to our condition'''
a[a > 50]

array([80, 75, 76, 53, 66, 73, 93, 92, 71, 86, 88, 94])

>* find out even numbers

In [18]:
a % 2 == 0

array([[ True,  True, False, False],
       [ True,  True,  True, False],
       [ True,  True, False,  True],
       [False, False,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [19]:
a[a % 2 == 0]

array([12, 14, 80, 22, 14, 38, 76, 66, 92, 86, 50, 88, 48, 48, 94, 46])

>* find the number greater than 50 and are even

In [20]:
(a > 50) & (a % 2 == 0)
# Note : here we are using bitwise & operator

array([[False, False, False, False],
       [ True, False, False, False],
       [False,  True, False,  True],
       [False, False,  True, False],
       [ True, False,  True, False],
       [False,  True, False, False]])

In [21]:
a[(a > 50) & (a % 2 == 0)]

array([80, 76, 66, 92, 86, 88, 94])

>* find all the numbers which are not divisible by 7

In [22]:
a % 7 != 0

array([[ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
a[a % 7 != 0]

array([12, 45, 17, 80, 22, 75, 38, 76, 53, 66, 73, 93, 92, 71, 86, 50, 88,
       48, 48, 94, 46, 41])

In [24]:
# we want these values to be zero
a[a % 7 != 0] = 0
print(a)

[[ 0 14  0  0]
 [ 0  0 14  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]
