In [1]:
import numpy as np

# 1. Broadcasting
* The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed. 
* If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-singular shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes

>* same shape

In [2]:
'''NumPy operations are usually done on pairs of 
arrays on an element-by-element basis. 
In the simplest case, the two arrays must have 
exactly the same shape, as in the following example:'''

a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


>* different shape

In [3]:
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print("answer is :",a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
answer is : [[0 2 4]
 [3 5 7]]


In [4]:
a3=np.arange(9).reshape(3,3)
a4=np.arange(3).reshape(1,3)

print("a3 array:",a3)
print("a4 array:",a4)

print("answer is :",a3+a4)

a3 array: [[0 1 2]
 [3 4 5]
 [6 7 8]]
a4 array: [[0 1 2]]
answer is : [[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


# 2. Rules for Broadcasting

**1. Make the two arrays have the same number of dimensions.**
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.

**3. Note :**
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

![](broadcasting.png)

In [5]:
# If x=m and y=n, operation will take place

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

a1+a2

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [6]:
'''If x=1 and y=n (n=3) then also operation will take place
(same dimension(2D)) (different shape)'''
a3 = np.arange(3).reshape(1,3) 
a4 = np.arange(12).reshape(4,3)

print(a3)
print(a4)

a3 + a4

[[0 1 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [7]:
a5=np.arange(3).reshape(3,1)
a6=np.arange(12).reshape(3,4)

print(a5)
print(a6)

a5+a6

[[0]
 [1]
 [2]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [8]:
'''here a 2D and b is 1D,
b will be streched up to (1,3) so it is 2D now,
now it is ready for broadcasting'''
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [9]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

print(a+b)
# it will throw an error

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
# if x=1 and y!=n then operation will not take place
a5=np.arange(3).reshape(1,3)
a6=np.arange(12).reshape(3,4)

print(a5)
print(a6)
# for addition it will throw an error
a5+a6

##### we will get this error from the above cell
>ValueError: **operands could not be broadcast together with shapes (1,3) (3,4)** 

In [10]:
# If x=1 and n=1 then y==m, operation will take place

a11=np.arange(3).reshape(1,3)
a12=np.arange(4).reshape(4,1)

print(a11)
print(a12)
a11+a12

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [11]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [12]:
# If x=1 and y=1, then operation will take place no matter what

a13=np.arange(1,2).reshape(1,1)
a14=np.arange(20).reshape(5,4)

print(a13)
print(a14)
a13+a14

[[1]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [13]:
# if they are of different dimensions

a15=np.arange(4)
a16=np.arange(20).reshape(5,4)

print(a15)
print(a16)
a15+a16

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])

In [14]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [15]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [16]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [17]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 