In [2]:
import numpy as np

### np.sort
* Return a sorted copy of an array.

In [3]:
a = np.random.randint(1,100,15)
a

array([64,  3, 79, 55, 72, 93, 38,  4, 50, 99, 73, 17, 90, 63, 52])

In [4]:
np.sort(a)
# we will get in ascending order

array([ 3,  4, 17, 38, 50, 52, 55, 63, 64, 72, 73, 79, 90, 93, 99])

In [5]:
np.sort(a)[::-1]
# for descending order

array([99, 93, 90, 79, 73, 72, 64, 63, 55, 52, 50, 38, 17,  4,  3])

In [6]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[33, 54, 89, 74],
       [82, 97, 59, 83],
       [17, 26, 92, 17],
       [78, 35, 68, 25],
       [50, 90, 96, 71],
       [59, 32, 65, 50]])

In [7]:
np.sort(b,axis=0)
# column wise sorting

array([[17, 26, 59, 17],
       [33, 32, 65, 25],
       [50, 35, 68, 50],
       [59, 54, 89, 71],
       [78, 90, 92, 74],
       [82, 97, 96, 83]])

### np.append
* The numpy.append() appends values along the mentioned axis at the end of the array
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [8]:
a = np.random.randint(1,100,15)
a

array([63, 41, 38, 56, 33, 38, 75,  9, 40, 61, 76, 28, 11, 67, 66])

In [9]:
np.append(a,100)

array([ 63,  41,  38,  56,  33,  38,  75,   9,  40,  61,  76,  28,  11,
        67,  66, 100])

In [10]:
# append in 2D column
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[72, 66, 37,  6],
       [ 9,  2, 85, 22],
       [97, 25, 50, 79],
       [ 5, 72, 72, 64],
       [51, 20, 87, 32],
       [96, 26, 70, 13]])

In [11]:
# suppose we want to append one column in the last
np.append(b,np.ones((b.shape[0],1)),axis=1)
# here b.shape[0] will give the number of rows in the b array

array([[72., 66., 37.,  6.,  1.],
       [ 9.,  2., 85., 22.,  1.],
       [97., 25., 50., 79.,  1.],
       [ 5., 72., 72., 64.,  1.],
       [51., 20., 87., 32.,  1.],
       [96., 26., 70., 13.,  1.]])

### np.concatenate
* numpy.concatenate() function concatenate a sequence of arrays along an existing axis.
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [12]:
c =  np.arange(6).reshape(2,3)
d =  np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d),axis=0)
# row wise concatination

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d),axis=1)
# column wise concatination         

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique
* With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [15]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
e

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [16]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims
* With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [17]:
a = np.random.randint(1,100,15)
a

array([88, 56, 24, 23, 41, 43,  2, 39, 64, 74, 35, 17, 96, 75, 40])

In [18]:
# a is a 1D array. we can convert it to 2D array
np.expand_dims(a,axis=0)
# we will get 2D array with row dimensions

array([[88, 56, 24, 23, 41, 43,  2, 39, 64, 74, 35, 17, 96, 75, 40]])

In [19]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [20]:
# a is a 1D array. we can convert it to 2D array
np.expand_dims(a,axis=1)
# we will get 2D array with column dimensions

array([[88],
       [56],
       [24],
       [23],
       [41],
       [43],
       [ 2],
       [39],
       [64],
       [74],
       [35],
       [17],
       [96],
       [75],
       [40]])

In [21]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where
* The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [22]:
a = np.random.randint(1,100,15)
a

array([86, 58, 29,  4, 73, 68, 81, 20, 58, 32, 79, 56, 25, 79,  9])

In [23]:
# find all the indices with value greater than 50
np.where(a>50)
# syntax = np.where(condition,True,False)

(array([ 0,  1,  4,  5,  6,  8, 10, 11, 13], dtype=int64),)

In [24]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0, 29,  4,  0,  0,  0, 20,  0, 32,  0,  0, 25,  0,  9])

In [25]:
# other way to replace all values > 50 with 0
a[np.where(a>50)]=0
a

array([ 0,  0, 29,  4,  0,  0,  0, 20,  0, 32,  0,  0, 25,  0,  9])

In [26]:
# we wannt to replace all even numbers with value zero
np.where(a%2 == 0,0,a)

array([ 0,  0, 29,  0,  0,  0,  0,  0,  0,  0,  0,  0, 25,  0,  9])

### np.argmax
* The numpy.argmax() function returns indices of the max element of the array in a particular axis.
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [27]:
a = np.random.randint(1,100,15)
a

array([98, 96, 78, 96, 18, 85, 73,  4, 43, 96, 81, 66, 51,  3, 69])

In [28]:
'''this will tell us that largest number 
in the arrayis on which position'''
np.argmax(a)

0

In [29]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[84, 29, 89, 91],
       [34,  9, 48, 47],
       [ 1, 49, 35, 45],
       [27, 28, 62, 95],
       [29, 64, 19, 33],
       [46,  9, 59,  2]])

In [30]:
np.argmax(b,axis=0)

array([0, 4, 0, 3], dtype=int64)

In [31]:
np.argmax(b,axis=1)

array([3, 2, 1, 3, 1, 2], dtype=int64)

### np.argmin

In [32]:
np.argmin(a)

13

### np.cumsum
* numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [33]:
a = np.random.randint(1,100,15)
a

array([20, 82, 52, 71, 14, 51, 13, 71, 66, 68, 22, 28, 88, 41, 20])

In [34]:
np.cumsum(a)

array([ 20, 102, 154, 225, 239, 290, 303, 374, 440, 508, 530, 558, 646,
       687, 707], dtype=int32)

In [35]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 7, 99, 69, 44],
       [75, 96, 67, 80],
       [30, 96, 70, 54],
       [ 1,  9, 77, 52],
       [50, 71, 56, 77],
       [ 9, 14, 66, 11]])

In [36]:
'''if we do not provide any axis in the 2D array then,
it will be converted in the 1D array and we will get the result'''
np.cumsum(b)

array([   7,  106,  175,  219,  294,  390,  457,  537,  567,  663,  733,
        787,  788,  797,  874,  926,  976, 1047, 1103, 1180, 1189, 1203,
       1269, 1280], dtype=int32)

In [37]:
np.cumsum(b,axis=0)

array([[  7,  99,  69,  44],
       [ 82, 195, 136, 124],
       [112, 291, 206, 178],
       [113, 300, 283, 230],
       [163, 371, 339, 307],
       [172, 385, 405, 318]], dtype=int32)

In [38]:
np.cumsum(b,axis=1)

array([[  7, 106, 175, 219],
       [ 75, 171, 238, 318],
       [ 30, 126, 196, 250],
       [  1,  10,  87, 139],
       [ 50, 121, 177, 254],
       [  9,  23,  89, 100]], dtype=int32)

### np.cumprod

In [39]:
a = np.random.randint(1,100,15)
a

array([48, 12, 97, 37, 71, 61, 99, 95, 30, 21, 97, 16,  1, 79, 28])

In [40]:
np.cumprod(a)

array([         48,         576,       55872,     2067264,   146775744,
         363385792,  1615455040, -1150593856,  -158077312,   975343744,
         119062656,  1905002496,  1905002496,   171341824,   502603776],
      dtype=int32)

### np.percentile
* numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [41]:
a = np.random.randint(1,100,15)
a

array([82, 11, 71, 16, 74, 27, 83, 87, 34, 31, 86, 42, 27, 71, 35])

In [42]:
np.percentile(a,100)
# 100th percentile is maximum

87.0

In [43]:
np.percentile(a,90)

84.8

In [44]:
np.percentile(a,0)
# 0 percentile is min

11.0

In [45]:
np.percentile(a,50)
# 50th percentile is median

42.0

### np.histogram
* Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [46]:
a = np.random.randint(1,100,15)
a

array([23, 40, 21, 27, 30, 87, 78, 70, 85, 20, 51,  3, 19, 94, 62])

In [47]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90])

(array([1, 1, 4, 1, 1, 1, 1, 2, 2], dtype=int64),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

### np.corrcoef
* Return Pearson product-moment correlation coefficients.
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [48]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [49]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin
* With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [50]:
a = np.random.randint(1,100,15)
a

array([88, 34, 16, 14, 95, 92, 22, 22, 89,  7, 93, 19, 85, 79, 76])

In [51]:
# we want to search several items at a time
items = [10,20,30,40,50,60,70,77,83,90]

In [52]:
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [53]:
a[np.isin(a,items)]

array([], dtype=int32)

### np.flip
* The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [54]:
a = np.random.randint(1,100,15)
a

array([74, 29, 99, 57, 97, 72, 21, 47, 34, 20, 40, 32, 13, 77, 85])

In [55]:
np.flip(a)

array([85, 77, 13, 32, 40, 20, 34, 47, 21, 72, 97, 57, 99, 29, 74])

In [56]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[22, 84, 93, 94],
       [71, 55, 57, 68],
       [77, 96, 45, 86],
       [82, 92, 23, 10],
       [60, 71,  5, 96],
       [49, 97, 57, 37]])

In [57]:
np.flip(b)

array([[37, 57, 97, 49],
       [96,  5, 71, 60],
       [10, 23, 92, 82],
       [86, 45, 96, 77],
       [68, 57, 55, 71],
       [94, 93, 84, 22]])

In [58]:
np.flip(b,axis=0)

array([[49, 97, 57, 37],
       [60, 71,  5, 96],
       [82, 92, 23, 10],
       [77, 96, 45, 86],
       [71, 55, 57, 68],
       [22, 84, 93, 94]])

In [59]:
np.flip(b,axis=1)

array([[94, 93, 84, 22],
       [68, 57, 55, 71],
       [86, 45, 96, 77],
       [10, 23, 92, 82],
       [96,  5, 71, 60],
       [37, 57, 97, 49]])

### np.put
* The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [60]:
a = np.random.randint(1,100,15)
a

array([73, 81, 72, 60, 25, 95, 42,  2, 13, 20, 83, 33, 98, 66, 57])

In [61]:
np.put(a,[0,1,3],[100,20,43])
# inside the function a is array,second part is indices and then values
# this put function will do permanent change

In [62]:
a

array([100,  20,  72,  43,  25,  95,  42,   2,  13,  20,  83,  33,  98,
        66,  57])

### np.delete
* The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [63]:
a = np.random.randint(1,100,15)
a

array([44, 30, 48, 74, 20,  4,  6,  6, 22, 60, 41, 87, 67, 56,  9])

In [64]:
# suppose we want to delete the item 83 from the array a
np.delete(a,0)

array([30, 48, 74, 20,  4,  6,  6, 22, 60, 41, 87, 67, 56,  9])

In [65]:
# we can delete multiple items too
np.delete(a,[0,1,2,4,8])

array([74,  4,  6,  6, 60, 41, 87, 67, 56,  9])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

* **Note :** here we will get the result in form of numpy arrays only

In [66]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [67]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [68]:
np.intersect1d(m,n)

array([3, 4, 5])

In [69]:
np.setdiff1d(m,n)

array([1, 2])

In [70]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [71]:
np.in1d(m,1)

array([ True, False, False, False, False])

In [72]:
np.in1d(n,4)

array([False,  True, False, False, False])

### np.clip
* numpy.clip() function is used to Clip (limit) the values in an array.
* **reference :** https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [73]:
a = np.random.randint(1,100,15)
a

array([78, 83, 94, 86, 13, 27,  9, 88, 58, 38, 98, 81,  1, 13, 95])

In [74]:
np.clip(a, a_min=25, a_max=75)

array([75, 75, 75, 75, 25, 27, 25, 75, 58, 38, 75, 75, 25, 25, 75])

### np.swapaxes

### np.uniform

### np.count_nonzero

### np.tile
* **reference :** https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

###  np.repeat
* **reference :** https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

### np.allclose and equals